FROM quay.io/keycloak/keycloak:20.0.3

ARG KEYCLOAK_ADMIN
ENV KEYCLOAK_ADMIN $KEYCLOAK_ADMIN

ARG KEYCLOAK_ADMIN_PASSWORD
ENV KEYCLOAK_ADMIN_PASSWORD $KEYCLOAK_ADMIN_PASSWORD

# database setup
ARG DB_VENDOR=POSTGRES
ENV DB_VENDOR $DB_VENDOR

ARG DB_DATABASE=keycloak_db
ENV DB_DATABASE $DB_DATABASE

ARG PGHOST
ARG DB_ADDR=$PGHOST
ENV DB_ADDR $DB_ADDR

ARG PGPORT
ARG DB_PORT=$PGPORT
ENV DB_PORT $DB_PORT

ARG PGUSER
ARG DB_USER=$PGUSER
ENV DB_USER $DB_USER

ARG PGPASSWORD
ARG DB_PASSWORD=$PGPASSWORD
ENV DB_PASSWORD $DB_PASSWORD

EXPOSE 8080

CMD [ "start", "--optimized" ]
